version: 2
jobs:
  linux-trusty-py3-6-gcc7-build:
    docker:
      - image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/linux-trusty-py3.6-gcc7:220
        user: jenkins
        auth:
          username: circleci
          password: $CIRCLECI_IAM_PASSWORD
    resource_class: large
    steps:
    - run:
        name: Hello World
        command: |
          whoami
workflows:
  version: 2
  linux-trusty-py3-6-gcc7:
    jobs:
      - linux-trusty-py3-6-gcc7-build
          - filters:
              branches:
                only: circleci
