version: 2
jobs:
  linux_trusty_py3_6_gcc7_build:
    - run:
        name: Hello World
        command: |
          whoami
workflows:
  version: 2
  linux_trusty_py3_6_gcc7:
    jobs:
      - linux_trusty_py3_6_gcc7_build
          - filters:
              branches:
                only: circleci
