version: 2
jobs:
  linux_trusty_py3_6_gcc7_build:
    docker:
      - image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-trusty-py3.6-gcc7:226
        user: jenkins
        aws_auth:
          aws_access_key_id: AKIAIUHRTFRLXI6HBUCQ
          aws_secret_access_key: $CIRCLECI_AWS_SECRET_KEY
    resource_class: large
    steps:
    - checkout
    - run:
        name: Build
        command: |
          export SCCACHE_BUCKET=ossci-compiler-cache
          git submodule update --init
          .jenkins/pytorch/build.sh
          .jenkins/pytorch/test.sh
  linux_xenial_cuda9_2_cudnn7_py3_gcc7_build:
    docker:
      - image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda9.2-cudnn7-py3-gcc7:226
        user: jenkins
        aws_auth:
          aws_access_key_id: AKIAIUHRTFRLXI6HBUCQ
          aws_secret_access_key: $CIRCLECI_AWS_SECRET_KEY
    resource_class: large
    steps:
    - checkout
    - run:
        name: Build
        command: |
          export SCCACHE_BUCKET=ossci-compiler-cache
          #git submodule update --init
          #.jenkins/pytorch/build.sh
          #tar czf circleci-${CIRCLE_BUILD_NUM}.tgz $HOME/.local/lib/python*/site-packages/torch*
          mkdir -p $HOME/.local/flub
          touch $HOME/.local/flub/foo
          mkdir -p workspace
          tar czf workspace/flub.tgz $HOME/.local/flub
    - persist_to_workspace:
        #root: $HOME/.local/lib/python3.6/site-packages/
        root: workspace
        paths:
          - flub.tgz
  macos_10_13_py3:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Build
          command: |
            export SCCACHE_BUCKET=ossci-compiler-cache
            export BUILD_ENVIRONMENT=pytorch-macos-10.13-py3
            git submodule update --init
            chmod a+x .jenkins/pytorch/macos-build.sh
            .jenkins/pytorch/macos-build.sh
workflows:
  version: 2
  build:
    jobs:
      - linux_trusty_py3_6_gcc7_build
      - linux_xenial_cuda9_2_cudnn7_py3_gcc7_build
      - macos_10_13_py3
