version: 2
jobs:
  linux_trusty_py3_6_gcc7_build:
    docker:
      - image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-trusty-py3.6-gcc7:226
        user: jenkins
        aws_auth:
          aws_access_key_id: AKIAIUHRTFRLXI6HBUCQ
          aws_secret_access_key: $CIRCLECI_AWS_SECRET_KEY
    resource_class: large
    steps:
    - run:
        name: Build
        command: |
          export SCCACHE_BUCKET=ossci-compiler-cache
          .jenkins/pytorch/build.sh
workflows:
  version: 2
  linux_trusty_py3_6_gcc7:
    jobs:
      - linux_trusty_py3_6_gcc7_build:
          filters:
            branches:
              only: circleci
